### PR TITLE
Switch from npm to yarn

### PR DESCRIPTION
**Pull request by pascalw**
NPM would insist on resolving
https://github.com/Wakamai-Fondue/wakamai-fondue-engine.git#8be250aac307b27af7644a6ffc42e717c4cc3b1f
to git+ssh ¯\_(ツ)_/¯

Might be related to https://github.com/npm/npm/issues/19168

### CODE REVIEW

**Comment by pascalw** [comment]
Not sure what was going on last week, but this issue doesn't seem to occur anymore ¯\_(ツ)_/¯.

**Comment by garviand** [comment]
@pascalw I've been scouring the internet for answers to this question and you are the first person I've seen to bring up this exact issue. Is your solution to just use yarn instead of NPM? Sorry for the question on the random PR but I am struggling with this.

**Comment by pascalw** [comment]
Hi @garviand you mean the fact that NPM insists (insisted?) on resolving (some?) git dependencies to `git+ssh` instead of `https`? I never figured out what was going on here, when I looked into it a few days later it suddenly didn't occur anymore.

If I now add the exact dependency URL I added previously:

```
npm add https://github.com/Wakamai-Fondue/wakamai-fondue-engine.git#8be250aac307b27af7644a6ffc42e717c4cc3b1f
```

Then the module is resolved correctly to `git+https` in the package-lock.json:

```
"@wakamai-fondue/engine": {
       "version": "git+https://github.com/Wakamai-Fondue/wakamai-fondue-engine.git#8be250aac307b27af7644a6ffc42e717c4cc3b1f",
       "from": "git+https://github.com/Wakamai-Fondue/wakamai-fondue-engine.git#8be250aac307b27af7644a6ffc42e717c4cc3b1f",
       "requires": {
               "lib-font": "^2.0.5"
       }
}
```

The issue never occurred with Yarn, so it was something NPM specific.

**Comment by garviand** [comment]
Huh, that is absurd. Thanks for letting me know!

**Comment by ezewer** [comment]
I am actually experiencing the same issue: 

```console
node: v14.16.0
npm 6.14.11
```
going back to npm version 6.14.6 fixed the issue

**Pull request closed without merging**
